### ISSUE TITLE
I can't get the color picker to work with Materialize. Anyone have any ideas?

### ISSUE THREAD

**Issue by nratter** [kostia/jquery-minicolors-rails#19] opened 2016-01-28 17:04 UTC
I can't get the color picker to work with Materialize. Anyone have any ideas?

**Comment by kostia** [comment] 2016-01-28 17:06
@nratter Please provide more infos:
* How do you try to integrate the colorpicker?
* What is "Materialize" and how do you integrate it in your Rails app?
* What are the symptoms of not working?
* Rails version, version of this gem.

**Comment by nratter** [comment] 2016-01-28 17:16
- I've tried with simple form `as: :minicolors`, as well as the jquery method on a custom class
- http://materializecss.com/ - it is an alternative to bootstrap. I've installed using this gem: https://github.com/mkhairi/materialize-sass
- When selecting an input box, no color picker pops up
- Rails version: 4.2.4, this gem: 2.2.2

Thanks!

**Comment by kostia** [comment] 2016-01-28 17:25
Unfortunately I cannot reproduce the issue using the above setup:

<img width="248" alt="bildschirmfoto 2016-01-28 um 18 23 01" src="https://cloud.githubusercontent.com/assets/9946/12652733/76ebf9f0-c5ec-11e5-8f6d-e0feba2fc6c6.png">

Do you see any errors in the browser console?

**Comment by kostia** [comment] 2016-04-02 13:20
Can I close this one?

**Comment by nratter** [comment] 2016-04-02 13:50
Yep!

**Closed** 2016-04-02 14:22 UTC
